name: NASA PROJECT CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: true # This is required to prevent the tests from hanging
      MONGO_URL: mongodb://localhost/nasa
    strategy:
        matrix:
            node-version: [16.x, 20.x]
            mongo-version: ['4.4']
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from Github Actions # this will resolve our test cases and it will NOT hit our actual data
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongo-version }}
      - name: Install dependencies
        run: npm install
      - name: Run build for client
        run: npm run build --prefix client
      - name: Run tests
        run: npm test
#  deploy:
#    needs: build needs means it depends on another step